feat(tests-with-debugger): try new drone config

diff --git a/.drone.yml b/.drone.yml
--- a/.drone.yml
+++ b/.drone.yml
@@ -53,31 +53,6 @@ steps:
     commands:
       - cp /usr/local/bin/mina cli/bin/
 
-  - name: build
-    image: rust:1.71-buster
-    commands:
-      - apt-get update && apt-get install -y libssl-dev libjemalloc-dev jq
-      - rustup update nightly-2023-06-01 && rustup default nightly-2023-06-01
-      - rustup component add rustfmt
-      - cargo test --release -p cli
-      - cargo build --release -p cli --bin openmina
-      - cargo build --release --features scenario-generators -p openmina-node-testing && mv target/release/openmina-node-testing /usr/bin/openmina-node-testing-libp2p
-      - cargo build --release --features scenario-generators,p2p-webrtc -p openmina-node-testing && mv target/release/openmina-node-testing /usr/bin/openmina-node-testing-webrtc
-      # - cargo test --release --features scenario-generators --no-run --message-format=json -v | jq '.executable' | grep node_libp2p_only | xargs -I {} mv {} ./target/release/test_libp2p_only
-      # - cargo test --release --features scenario-generators,p2p-webrtc --no-run --message-format=json -v | jq '.executable' | grep node_libp2p_only | xargs -I {} mv {} ./target/release/test_libp2p_only_with_webrtc_compiled
-      # - cargo test --release --features scenario-generators,p2p-webrtc --no-run --message-format=json -v | jq '.executable' | grep node_libp2p_with | xargs -I {} mv {} ./target/release/test_libp2p_plus_webrtc
-
-  # - name: testing-framework-tests-libp2p-plus-webrtc
-  #   image: minaprotocol/mina-daemon:2.0.0rampup4-14047c5-buster-berkeley
-  #   commands:
-  #     - ./target/release/test_libp2p_plus_webrtc
-  #     - ./target/release/test_libp2p_only_with_webrtc_compiled
-
-  # - name: testing-framework-tests-libp2p-only
-  #   image: minaprotocol/mina-daemon:2.0.0rampup4-14047c5-buster-berkeley
-  #   commands:
-  #     - ./target/release/test_libp2p_only
-
   - name: debugger
     image: openmina/mina-network-debugger:31f2ca11
     privileged: true
@@ -92,10 +67,22 @@ steps:
       RUST_LOG: "info"
       DB_PATH: "/tmp/db"
 
+  - name: build
+    image: rust:1.71-buster
+    commands:
+      - apt-get update && apt-get install -y libssl-dev libjemalloc-dev jq
+      - rustup update nightly-2023-06-01 && rustup default nightly-2023-06-01
+      - rustup component add rustfmt
+      - cargo test --release -p cli
+      - cargo build --release -p cli --bin openmina
+      - cargo build --release --features scenario-generators -p openmina-node-testing && mv target/release/openmina-node-testing target/release/openmina-node-testing-libp2p
+      - cargo build --release --features scenario-generators,p2p-webrtc -p openmina-node-testing && mv target/release/openmina-node-testing target/release/openmina-node-testing-webrtc
+
   - name: solo-webrtc-sync-root-snarked-ledger
     image: minaprotocol/mina-daemon:2.0.0rampup4-14047c5-buster-berkeley
     failure: ignore
     commands:
+      - cp target/release/openmina-node-testing-webrtc /usr/bin/openmina-node-testing-webrtc
       - ./scripts/runner openmina-node-testing-webrtc scenarios-generate --name solo-node-sync-root-snarked-ledger
     environment:
       BPF_ALIAS: "3c41383994b87449625df91769dff7b507825c064287d30fada9286f3f1cb15e-255.255.255.0"
@@ -104,6 +91,7 @@ steps:
     image: vladsimplestakingcom/mina-debugger:2.0.0rampup4-focal
     failure: ignore
     commands:
+      - cp target/release/openmina-node-testing-webrtc /usr/bin/openmina-node-testing-webrtc
       - ./scripts/runner openmina-node-testing-webrtc scenarios-generate --name solo-node-basic-connectivity-initial-joining
     environment:
       BPF_ALIAS: "3c41383994b87449625df91769dff7b507825c064287d30fada9286f3f1cb15e-255.255.255.1"
@@ -112,6 +100,7 @@ steps:
     image: vladsimplestakingcom/mina-debugger:2.0.0rampup4-focal
     failure: ignore
     commands:
+      - cp target/release/openmina-node-testing-webrtc /usr/bin/openmina-node-testing-webrtc
       - ./scripts/runner openmina-node-testing-webrtc scenarios-generate --name multi-node-basic-connectivity-initial-joining
     environment:
       BPF_ALIAS: "3c41383994b87449625df91769dff7b507825c064287d30fada9286f3f1cb15e-255.255.255.2"
@@ -120,6 +109,7 @@ steps:
     image: vladsimplestakingcom/mina-debugger:2.0.0rampup4-focal
     failure: ignore
     commands:
+      - cp target/release/openmina-node-testing-libp2p /usr/bin/openmina-node-testing-libp2p
       - ./scripts/runner openmina-node-testing-libp2p scenarios-generate --name solo-node-sync-root-snarked-ledger
     environment:
       BPF_ALIAS: "3c41383994b87449625df91769dff7b507825c064287d30fada9286f3f1cb15e-255.255.255.3"
@@ -128,6 +118,7 @@ steps:
     image: vladsimplestakingcom/mina-debugger:2.0.0rampup4-focal
     failure: ignore
     commands:
+      - cp target/release/openmina-node-testing-libp2p /usr/bin/openmina-node-testing-libp2p
       - ./scripts/runner openmina-node-testing-libp2p scenarios-generate --name solo-node-basic-connectivity-initial-joining
     environment:
       BPF_ALIAS: "3c41383994b87449625df91769dff7b507825c064287d30fada9286f3f1cb15e-255.255.255.4"
@@ -136,6 +127,7 @@ steps:
     image: vladsimplestakingcom/mina-debugger:2.0.0rampup4-focal
     failure: ignore
     commands:
+      - cp target/release/openmina-node-testing-libp2p /usr/bin/openmina-node-testing-libp2p
       - ./scripts/runner openmina-node-testing-libp2p scenarios-generate --name multi-node-basic-connectivity-initial-joining
     environment:
       BPF_ALIAS: "3c41383994b87449625df91769dff7b507825c064287d30fada9286f3f1cb15e-255.255.255.5"
@@ -144,6 +136,7 @@ steps:
     image: vladsimplestakingcom/mina-debugger:2.0.0rampup4-focal
     failure: ignore
     commands:
+      - cp target/release/openmina-node-testing-libp2p /usr/bin/openmina-node-testing-libp2p
       - ./scripts/runner openmina-node-testing-libp2p scenarios-generate --name solo-node-basic-connectivity-accept-incoming
     environment:
       BPF_ALIAS: "3c41383994b87449625df91769dff7b507825c064287d30fada9286f3f1cb15e-255.255.255.6"
@@ -152,6 +145,7 @@ steps:
     image: vladsimplestakingcom/mina-debugger:2.0.0rampup4-focal
     failure: ignore
     commands:
+      - cp target/release/openmina-node-testing-libp2p /usr/bin/openmina-node-testing-libp2p
       - ./scripts/runner openmina-node-testing-libp2p scenarios-generate --name multi-node-basic-connectivity-peer-discovery
     environment:
       BPF_ALIAS: "3c41383994b87449625df91769dff7b507825c064287d30fada9286f3f1cb15e-255.255.255.7"
@@ -165,35 +159,6 @@ steps:
       OPENMINA_P2P_SEC_KEY: 5JDRBqXfHm4Xne1QKUJyg9FKRfwN6gtduZb7nVYHg2F1BmwPynT
     commands:
       - RUST_LOG=info openmina-bootstrap-sandbox --path='/tmp/mina-record' --listen='/ip4/0.0.0.0/tcp/8302' --chain-id=$CHAIN_ID replay 234
-
-  # - name: empty
-  #   image: vladsimplestakingcom/bootstrap-rr:graphql
-  #   pull: always
-  #   detach: true
-  #   environment:
-  #     # 12D3KooWBk4vJzxBZcwDXEae91mPLxJZks2pUCpDJP1zmCjx95ai
-  #     OPENMINA_P2P_SEC_KEY: 5KRTpP4DczohhCkYVSZCHNzEF2t8Lig1EwbUPkR7TT2b4gMYYer
-  #     RUST_LOG: info
-  #   commands:
-  #     - openmina-bootstrap-sandbox --listen='/ip6/::/tcp/8302' --listen='/ip4/0.0.0.0/tcp/8302' empty
-
-  # - name: ocaml1
-  #   image: minaprotocol/mina-daemon:2.0.0rampup3-bfd1009-buster-berkeley
-  #   detach: true
-  #   environment:
-  #     MINA_LIBP2P_PASS: _
-  #   commands:
-  #     - curl https://raw.githubusercontent.com/MinaProtocol/mina/bfd1009/genesis_ledgers/berkeley.json -o /berkeley.json
-  #     - mkdir /key && chmod 700 /key
-  #     - echo '{"box_primitive":"xsalsa20poly1305","pw_primitive":"argon2i","nonce":"6MNkZnzpgwLHBA28BLzmEcxv4uAHqv52498evUP","pwsalt":"9YzR5Eb7faseS8XgE74Q7KbmrKs7","pwdiff":[134217728,6],"ciphertext":"7DrdaPt1vmgRVT8L4LcHyq6WSwzzxK1XfnZAwwtwWZRUpaChfetKyKrBBSuW3X99QUMebL8gCmuW9yq9k6CbpByvfWuRNEnejGHtXNrmyjJdoU5fd656CFjs4kXPUbpDLLwf4PD4axa89TDh5xCPENsqmigE38UuLn42TNix8sqyyGuVnyNXvP2pjDKKVU6rWatw83w8ijP97HXzeV9vwq2YudRFr4URdi11hiyVjvQ5DCmF3yNYJs5RgJw94AteZqfr2CH1FsdRA3nhiBLavreFZ53WEJnxJ69xt"}' > /key/key
-  #     - echo '12D3KooWKLzGWSdFAQGEAtrHan1TTwu7idagcZ83X6MXWfUJNiTU' > /key/key.peerid
-  #     - chmod 600 /key/*
-  #     - apt-get update && apt-get install -y netcat
-  #     - netcat -l -p 9000 || true
-  #     - mina daemon --external-port 8302 --config-file /berkeley.json --libp2p-keypair /key/key
-  #         --log-level Debug --insecure-rest-server
-  #         --peer /dns4/empty/tcp/8302/p2p/12D3KooWBk4vJzxBZcwDXEae91mPLxJZks2pUCpDJP1zmCjx95ai
-  #         --direct-peer /dns4/openmina1/tcp/10000/p2p/$OPENMINA1_LIBP2P_ID
 
   - name: openmina1
     image: *snark-worker-image
@@ -236,71 +201,61 @@ steps:
     commands:
       - sleep 180
       - RUST_LOG=debug timeout 3600s openmina-bootstrap-sandbox --path='/tmp/mina-record' --chain-id=$CHAIN_ID test-graphql 234 http://openmina3:10000/graphql
-  # - name: test-bootstrap-openmina-to-mina
-  #   image: vladsimplestakingcom/bootstrap-rr:graphql
-  #   pull: always
-  #   environment:
-  #     RUST_LOG: debug
+
+  # - name: test-snark-work
+  #   image: alpine
   #   commands:
-  #     - apt-get update && apt-get install -y netcat
-  #     - echo "ready" | netcat -q 1 ocaml1 9000
-  #     - sleep 180
-  #     - timeout 3600s openmina-bootstrap-sandbox --path='/tmp/mina-record' --chain-id=$CHAIN_ID test-graphql 234 http://ocaml1:3085/graphql
+  #     - apk add curl jq
+  #     - |
+  #       c() {
+  #          n=$$1
+  #          path=$$2
+  #          shift 2
+  #          curl -s http://openmina$$n:10000/$$path "$$@"
+  #       }
+  #     - |
+  #       assert() {
+  #         eval $2 || {
+  #           echo "[failed] $1: '$2'"
+  #           exit 1
+  #         }
+  #       }
+  #     - |
+  #       TOTAL_WORK_TODO=$$(c 1 snark-pool/jobs | jq 'length')
+  #       echo "TOTAL_WORK_TODO=$TOTAL_WORK_TODO"
+  #       LOCAL_WORK=0
+  #       for t in $(seq 10); do
+  #         WORKERS=$$(c 1 snarker/workers | jq '[.[] | select(.status.kind != "None")] | length')
+  #         assert 'active workers > 0' '[ $$WORKERS -gt 0 ]'
 
-  - name: test-snark-work
-    image: alpine
-    commands:
-      - apk add curl jq
-      - |
-        c() {
-           n=$$1
-           path=$$2
-           shift 2
-           curl -s http://openmina$$n:10000/$$path "$$@"
-        }
-      - |
-        assert() {
-          eval $2 || {
-            echo "[failed] $1: '$2'"
-            exit 1
-          }
-        }
-      - |
-        TOTAL_WORK_TODO=$$(c 1 snark-pool/jobs | jq 'length')
-        echo "TOTAL_WORK_TODO=$TOTAL_WORK_TODO"
-        LOCAL_WORK=0
-        for t in $(seq 10); do
-          WORKERS=$$(c 1 snarker/workers | jq '[.[] | select(.status.kind != "None")] | length')
-          assert 'active workers > 0' '[ $$WORKERS -gt 0 ]'
+  #         COMMITMENTS_IN_PROGRESS=$$(c 1 snark-pool/jobs | jq "[.[] | select(.snark == null and .commitment.snarker == \"$OPENMINA1_SNARKER_KEY\")] | length")
+  #         assert 'local commitments in progress fewer than local workers' '[ $$COMMITMENTS_IN_PROGRESS -le $$WORKERS ]'
 
-          COMMITMENTS_IN_PROGRESS=$$(c 1 snark-pool/jobs | jq "[.[] | select(.snark == null and .commitment.snarker == \"$OPENMINA1_SNARKER_KEY\")] | length")
-          assert 'local commitments in progress fewer than local workers' '[ $$COMMITMENTS_IN_PROGRESS -le $$WORKERS ]'
-
-          LW=$$(c 1 snark-pool/jobs | jq "[.[] | select(.snark.snarker == \"$OPENMINA1_SNARKER_KEY\")] | length")
-          assert 'local snarks number do not decrease' '[ $$LOCAL_WORK -le $$LW ]'
-          LOCAL_WORK=$$LW
+  #         LW=$$(c 1 snark-pool/jobs | jq "[.[] | select(.snark.snarker == \"$OPENMINA1_SNARKER_KEY\")] | length")
+  #         assert 'local snarks number do not decrease' '[ $$LOCAL_WORK -le $$LW ]'
+  #         LOCAL_WORK=$$LW
 
 
-          sleep 30
-        done
+  #         sleep 30
+  #       done
 
-        c 1 snark-pool/jobs > jobs.json
+  #       c 1 snark-pool/jobs > jobs.json
 
-        assert 'local work exists' '[ $$LOCAL_WORK -gt 0 ]'
+  #       assert 'local work exists' '[ $$LOCAL_WORK -gt 0 ]'
 
-        TOTAL_WORK=$$(jq '[.[] | select(.snark != null)] | length' jobs.json)
-        LOCAL_WORK=$$(jq "[.[] | select(.snark != null and .snark.snarker == \"$OPENMINA1_SNARKER_KEY\")] | length" jobs.json)
-        NON_LOCAL_WORK=$$(jq "[.[] | select(.snark != null and .snark.snarker != \"$OPENMINA1_SNARKER_KEY\")] | length" jobs.json)
-        echo "TOTAL_WORK=$$TOTAL_WORK"
-        echo "LOCAL_WORK=$$LOCAL_WORK"
-        echo "NON_LOCAL_WORK=$$NON_LOCAL_WORK"
-        assert 'non-local work exists' '[ $$NON_LOCAL_WORK -gt 0 ]'
+  #       TOTAL_WORK=$$(jq '[.[] | select(.snark != null)] | length' jobs.json)
+  #       LOCAL_WORK=$$(jq "[.[] | select(.snark != null and .snark.snarker == \"$OPENMINA1_SNARKER_KEY\")] | length" jobs.json)
+  #       NON_LOCAL_WORK=$$(jq "[.[] | select(.snark != null and .snark.snarker != \"$OPENMINA1_SNARKER_KEY\")] | length" jobs.json)
+  #       echo "TOTAL_WORK=$$TOTAL_WORK"
+  #       echo "LOCAL_WORK=$$LOCAL_WORK"
+  #       echo "NON_LOCAL_WORK=$$NON_LOCAL_WORK"
+  #       assert 'non-local work exists' '[ $$NON_LOCAL_WORK -gt 0 ]'
 
-        # TOTAL_COMMITMENTS=$$(jq "[.[] | select(.commitment != null)] | length" jobs.json)
-        # NON_LOCAL_COMMITMENTS=$$(jq "[.[] | select(.commitment != null and .commitment.commitment.snarker != \"$OPENMINA1_SNARKER_KEY\")] | length" jobs.json)
-        # echo "TOTAL_COMMITMENTS=$$TOTAL_COMMITMENTS"
-        # echo "NON_LOCAL_COMMITMENTS=$$NON_LOCAL_COMMITMENTS"
-        # assert 'non-local commintment exists' '[ $$NON_LOCAL_COMMITMENTS -gt 0 ]'
+  #       # TOTAL_COMMITMENTS=$$(jq "[.[] | select(.commitment != null)] | length" jobs.json)
+  #       # NON_LOCAL_COMMITMENTS=$$(jq "[.[] | select(.commitment != null and .commitment.commitment.snarker != \"$OPENMINA1_SNARKER_KEY\")] | length" jobs.json)
+  #       # echo "TOTAL_COMMITMENTS=$$TOTAL_COMMITMENTS"
+  #       # echo "NON_LOCAL_COMMITMENTS=$$NON_LOCAL_COMMITMENTS"
+  #       # assert 'non-local commintment exists' '[ $$NON_LOCAL_COMMITMENTS -gt 0 ]'
 
 ---
 kind: pipeline
